### ISSUE TITLE
Write standard job launcher function

### ISSUE THREAD

**Issue by pbilling** [StanfordBioinformatics/trellis-mvp-functions#36]

**Comment by pbilling** [comment]
Another challenge: How do I specify output URIs? These paths involve multiple variables including ones from the Trellis config, JobLauncher config, and variables defined at runtime (task-id).

**Comment by pbilling** [comment]
The solution I'm settling on only includes input-specific variables in the task template. Other values (from Trellis, defined at runtime) will be applied uniformly to all job outputs, regardless of task. This changes the ordering of the output elements, but not the content.

An example where bold values have been rearranged and italic values will be defined in the job_launcher function while non-italicized values come from a task template:

Old: gs://{OUT_BUCKET}/**{plate}/{sample}**/{task.name}/{job_id}/output/{sample}_{read_group}.ubam

New:  _gs://{OUT_BUCKET}/{task.name}/{job_id}/output/_**{plate}/{sample}**/{sample}_{read_group}.ubam

Here, the plate and sample values have been moved to the end because they (and read_group) are all gotten from the properties of one of the input objects using the string ".format()" method. The structure and types of these input-derived properties may also change from task to task. For instance, if a task requires combining inputs from multiple samples then it doesn't make sense to put them in a path with a singe set of plate/sample values.

Conversely, the {OUT_BUCKET}, {task.name}, and {job_id} values can be applied uniformly to all jobs and their structure will be defined in the job_launcher function. So, the new structure of the outputs reflects a functional organization of values based on how Trellis organizes tasks

**Comment by pbilling** [comment]
- [ ] Write create_job_dict() method
- [ ] Write _get_job_values() method for translating template inputs/envs to values
- [ ] Write _get_output_values() method for translating template outputs to values
- [ ] Write _get_label_values() method for translating template labels to values

**Comment by pbilling** [comment]
Methods for populating dsub values from template implemented in 2b2754fc.

**Comment by pbilling** [comment]
Create a Cloud Build trigger for Job Launcher function

- [ ] Create `google_cloudbuild_trigger` resource in terraform (trellis-mvp-terraform/3-trellis/build-triggers-qc-functions.tf)
- [ ] Create `google_pubsub_topic` resource in terraform (trellis-mvp-terraform/3-trellis/pubsub-topics.tf)
- [ ] Create Cloud Build deployment script in function source directory

**Comment by pbilling** [comment]
Forgot to implement `parse_node_inputs()` and `parse_relationship_inputs()` functions. The `parse_inputs()` function was originally designed to perform job-specific QA on the inputs, which is an idea I like, but how to do it in a generic manner?

**Comment by pbilling** [comment]
`AttributeError: 'QueryResponseReader' object has no attribute 'job_request'`

Probably need to upload new version of trellisdata package.

**Comment by pbilling** [comment]
**Task:** Update trellisdata package

- [ ] Add job_request attribute to DatabaseQuery class
- [ ] Add job_request attribute check to DatabaseQuery equality method
- [ ] Add JobLauncher class to trellisdata
- [ ] In trellisdata __init__.py file, import JobLauncher
- [ ] Add job_request attribute to QueryResponseWriter & Reader classes
- [ ] Update db-query to get job_request field from DatabaseQuery instances & pass to QueryResponseWriter object
- [ ] Update job-launcher function to get job_request field from QueryResponseReader object

**Comment by pbilling** [comment]
**Task**: Update trellisdata tests to check new job request features

**Comment by pbilling** [comment]
For testing, I'm using the sample name "test-sample-v1-3" in gcloud Secret Manager

**Comment by pbilling** [comment]
Status update: successfully launched first fastq-to-ubam job
